"""Generated-only admission and independent-book tests; no real BOOK or source.

Source tests exercise the real manifest/byte loader against generated files.
State-machine tests stub only code pins and the analysis backend; their passing
results are not evidence that the real saved archive/lineage adapter succeeded.
"""
from copy import deepcopy
import hashlib
import json
from pathlib import Path
import runpy
import sqlite3
import sys

import pytest

from quanta_agents.meta_v3 import saved_return_lineage_audit as subject
from quanta_agents.meta_v3.ledger import digest, serial


CLI = Path(__file__).resolve().parents[1] / 'scripts/run_v4_saved_return_lineage.py'


@pytest.fixture
def generated(tmp_path, monkeypatch):
    """Change only configured roots/pins, keeping manifest and loader real."""
    root = tmp_path / 'generated_root'; root.mkdir()
    sources = {}
    for name, role, body in [('generated_case.json', 'exposed_case', b'{"engineering_only":true}'),
                             ('generated_metadata.json', 'metadata', b'{"no_market_values":true}'),
                             ('generated_archive.json.gz', 'physical_exposed_2017_2021_archive', b'generated bytes; never decoded')]:
        path = root / name; path.write_bytes(body)
        sources[name] = (hashlib.sha256(body).hexdigest(), role, 1024)
    monkeypatch.setattr(subject, 'ROOT', root)
    monkeypatch.setattr(subject, 'SOURCES', sources)
    monkeypatch.setattr(subject, 'BOOK', root / 'independent_input_lineage_audits.sqlite3')
    return root


def no_source_reads(monkeypatch, paths):
    original = Path.open; paths = {Path(p) for p in paths}
    def guarded(path, *args, **kwargs):
        if path in paths:
            pytest.fail('rejected metadata opened input source bytes')
        return original(path, *args, **kwargs)
    monkeypatch.setattr(Path, 'open', guarded)


@pytest.mark.parametrize('change', ['relative_path','absolute_path','role','hash','selected_dates','selected_symbol',
    'selected_count','physical_partition','physical_range','previous_anchor','allow_csv','allow_strategy',
    'allow_formal','source_byte_cap','archive_expansion_cap','source_order','missing_source','extra_field'])
def test_fixed_manifest_rejects_changes_before_reading_any_source(generated, monkeypatch, change):
    manifest = subject.metadata_manifest(); original = deepcopy(manifest)
    if change == 'relative_path': manifest['sources'][0]['relative_path'] = 'alias.json'
    if change == 'absolute_path': manifest['sources'][0]['path'] = str(generated / 'alias.json')
    if change == 'role': manifest['sources'][0]['role'] = 'document_identity_only'
    if change == 'hash': manifest['sources'][0]['sha256'] = '0' * 64
    if change == 'selected_dates': manifest['selected_date_range'] = ['2024-01-02','2024-12-31']
    if change == 'selected_symbol': manifest['selected_symbol'] = 'sh600006'
    if change == 'selected_count': manifest['selected_sessions'] = 243
    if change == 'physical_partition': manifest['physical_market_partition'] = 'sealed_2024_2025'
    if change == 'physical_range': manifest['physical_market_date_range'] = ['2017-01-01','2025-12-31']
    if change == 'previous_anchor': manifest['explicit_previous_anchor'] = '2019-01-02'
    if change == 'allow_csv': manifest['original_csv_reads_allowed'] = True
    if change == 'allow_strategy': manifest['strategy_execution_allowed'] = True
    if change == 'allow_formal': manifest['formal_release_allowed'] = True
    if change == 'source_byte_cap': manifest['sources'][0]['max_bytes'] *= 2
    if change == 'archive_expansion_cap': manifest['max_expanded_archive_bytes'] *= 2
    if change == 'source_order': manifest['sources'].reverse()
    if change == 'missing_source': manifest['sources'].pop()
    if change == 'extra_field': manifest['caller_approval'] = True
    no_source_reads(monkeypatch, [r['path'] for r in original['sources']])
    with pytest.raises(ValueError, match='scope changed'): subject._read_inputs(manifest)
    assert not subject.BOOK.exists()


def test_real_loader_reads_only_generated_bound_sources_and_retains_inventory(generated):
    manifest = subject.metadata_manifest(); before = digest(manifest)
    blobs, inventory = subject._read_inputs(manifest)
    assert set(blobs) == set(subject.SOURCES)
    assert len(inventory) == 3 and digest(manifest) == before
    for entry in inventory:
        content = blobs[entry['relative_path']]
        assert hashlib.sha256(content).hexdigest() == entry['sha256']
        assert entry['bytes_read'] == len(content) <= entry['max_bytes']
    assert not subject.BOOK.exists()


@pytest.mark.parametrize('change', ['missing','oversized','redirected'])
def test_current_source_metadata_is_checked_before_first_byte(generated, monkeypatch, change):
    manifest = subject.metadata_manifest(); source = Path(manifest['sources'][0]['path'])
    if change == 'missing': source.unlink()
    if change == 'oversized': source.write_bytes(b'x' * 1025)
    if change == 'redirected':
        original = Path.resolve
        def redirect(path, *args, **kwargs):
            return generated / 'redirected.json' if path == source else original(path, *args, **kwargs)
        monkeypatch.setattr(Path, 'resolve', redirect)
    no_source_reads(monkeypatch, [r['path'] for r in manifest['sources']])
    with pytest.raises(ValueError, match='metadata'): subject._read_inputs(manifest)


def test_bound_content_tamper_rejects_without_reading_next_source(generated, monkeypatch):
    manifest = subject.metadata_manifest(); first = Path(manifest['sources'][0]['path'])
    first.write_bytes(b'changed generated content')
    no_source_reads(monkeypatch, [r['path'] for r in manifest['sources'][1:]])
    with pytest.raises(ValueError, match='source changed'): subject._read_inputs(manifest)


@pytest.fixture
def state_machine(generated, monkeypatch):
    """Backend stub is explicitly limited to durable-consumption behavior."""
    calls = []
    pins = {'generated_test_code.py': '1' * 64}
    monkeypatch.setattr(subject, 'code_pins', lambda: dict(pins))
    def backend(manifest, *, as_of):
        with sqlite3.connect(subject.BOOK.resolve().as_uri() + '?mode=ro', uri=True) as connection:
            connection.execute('PRAGMA query_only=ON')
            row = connection.execute('SELECT state,manifest FROM audits WHERE subject=?', (subject.SUBJECT,)).fetchone()
            assert row[0] == 'CONSUMED'
            frozen = json.loads(row[1]); assert frozen['scope'] == manifest and frozen['as_of'] == as_of
            assert connection.execute('SELECT COUNT(*) FROM events WHERE subject=?', (subject.SUBJECT,)).fetchone()[0] == 1
        calls.append({'manifest': deepcopy(manifest), 'as_of': as_of})
        return {'kind': 'generated_backend_probe_only', 'formal_target_success': False,
                'source_authenticated': False, 'account_executed': False, 'strategy_executed': False}
    monkeypatch.setattr(subject, 'analyze_saved_inputs', backend)
    return calls, pins


def test_consume_is_committed_before_backend_and_complete_has_two_events(generated, state_machine):
    calls, _ = state_machine; result = subject.run(generated/'output')
    assert len(calls) == 1 and result['state'] == 'COMPLETE' and result['event_count'] == 2
    assert result['manifest']['scope']['prior_preparation_exposure'] is True
    assert result['receipt']['formal_target_success'] is False
    assert json.loads((generated/'output/intent.json').read_text(encoding='utf-8')) == result['manifest']
    assert result['receipt']['report_file_sha256'] == hashlib.sha256((generated/'output/report.json').read_bytes()).hexdigest()


def test_original_subject_cannot_retry_by_same_or_new_output_alias(generated, state_machine):
    calls, _ = state_machine; subject.run(generated/'first')
    with pytest.raises(ValueError): subject.run(generated/'first')
    with pytest.raises(ValueError, match='already consumed'): subject.run(generated/'renamed_output')
    assert len(calls) == 1 and not (generated/'renamed_output').exists()
    assert subject.status()['state'] == 'COMPLETE'


def test_direct_consume_duplicate_subject_and_second_settle_are_refused(generated, state_machine):
    manifest = subject.metadata_manifest(); pins = subject.code_pins()
    subject._consume(manifest, generated/'first', pins, '2026-09-08T00:00:00+00:00')
    with pytest.raises(ValueError, match='already consumed'):
        subject._consume(manifest, generated/'alias', pins, '2026-09-09T00:00:00+00:00')
    receipt = {'subject':subject.SUBJECT,'formal_target_success':False,'test_only':True}
    subject._settle('INCOMPLETE_TERMINAL', receipt)
    with pytest.raises(ValueError, match='no longer unresolved'): subject._settle('COMPLETE', receipt)
    assert subject.status()['receipt'] == receipt


def test_backend_exception_is_terminal_and_retains_original_consumption(generated, state_machine, monkeypatch):
    calls = []
    def failing(*args, **kwargs):
        assert subject.status()['state'] == 'CONSUMED'; calls.append(1)
        raise OSError('generated archive read failure')
    monkeypatch.setattr(subject, 'analyze_saved_inputs', failing)
    with pytest.raises(OSError, match='generated archive'): subject.run(generated/'first')
    saved = subject.status()
    assert saved['state'] == 'INCOMPLETE_TERMINAL' and saved['event_count'] == 2
    assert saved['receipt']['original_consumption_preserved'] is True
    assert (generated/'first/intent.json').exists() and (generated/'first/failure.json').exists()
    with pytest.raises(ValueError, match='already consumed'): subject.run(generated/'second')
    assert calls == [1]


@pytest.mark.parametrize('interruption', [KeyboardInterrupt, SystemExit])
def test_baseexception_leaves_consumed_unknown_and_never_redispatches(generated, state_machine, monkeypatch, interruption):
    calls=[]
    def interrupted(*args, **kwargs):
        calls.append(1); raise interruption('generated uncertain dispatch')
    monkeypatch.setattr(subject, 'analyze_saved_inputs', interrupted)
    with pytest.raises(interruption): subject.run(generated/'first')
    result=subject.status()
    assert result['state']=='CONSUMED' and result['receipt'] is None and result['event_count']==1
    assert (generated/'first/intent.json').exists() and not (generated/'first/failure.json').exists()
    with pytest.raises(ValueError, match='already consumed'): subject.run(generated/'another')
    assert calls==[1]


def test_code_pin_drift_after_backend_cannot_settle_as_success_or_be_retried(generated, state_machine, monkeypatch):
    calls, pins = state_machine; original = subject.analyze_saved_inputs
    def changed(*args, **kwargs):
        report=original(*args, **kwargs); pins['generated_test_code.py']='2'*64; return report
    monkeypatch.setattr(subject, 'analyze_saved_inputs', changed)
    with pytest.raises(ValueError, match='code changed'): subject.run(generated/'first')
    assert subject.status()['state']=='INCOMPLETE_TERMINAL'
    assert not (generated/'first/report.json').exists()
    with pytest.raises(ValueError, match='already consumed'): subject.run(generated/'alias')
    assert len(calls)==1


def test_code_pin_drift_after_consumption_before_backend_reads_no_inputs(generated, state_machine, monkeypatch):
    calls, pins = state_machine; count = []
    def drift():
        count.append(1)
        return dict(pins) if len(count)==1 else {'generated_test_code.py':'2'*64}
    monkeypatch.setattr(subject, 'code_pins', drift)
    with pytest.raises(ValueError, match='before input read'): subject.run(generated/'first')
    saved=subject.status()
    assert calls==[] and saved['state']=='INCOMPLETE_TERMINAL' and saved['event_count']==2
    assert 'before input read' in saved['receipt']['message']
    with pytest.raises(ValueError, match='already consumed'):subject.run(generated/'alias')
    assert calls==[]


@pytest.mark.parametrize('kind',['unsupported_state','wrong_subject','true_success','missing_success'])
def test_settlement_rejects_foreign_or_success_claim_before_mutating_consumed_state(generated,state_machine,kind):
    subject._consume(subject.metadata_manifest(),generated/'first',subject.code_pins(),'2026-09-08T00:00:00+00:00')
    state='COMPLETE';receipt={'subject':subject.SUBJECT,'formal_target_success':False}
    if kind=='unsupported_state':state='RETRYABLE'
    if kind=='wrong_subject':receipt['subject']='another-audit'
    if kind=='true_success':receipt['formal_target_success']=True
    if kind=='missing_success':receipt.pop('formal_target_success')
    before=subject.BOOK.read_bytes()
    with pytest.raises(ValueError,match='invalid lineage terminal'):subject._settle(state,receipt)
    assert subject.BOOK.read_bytes()==before and subject.status()['state']=='CONSUMED'


def test_status_is_read_only_and_does_not_open_sources_or_backend(generated, state_machine, monkeypatch):
    subject.run(generated/'first'); before=subject.BOOK.read_bytes()
    monkeypatch.setattr(subject,'validate_manifest',lambda *a:pytest.fail('status attempted source metadata admission'))
    monkeypatch.setattr(subject,'_read_inputs',lambda *a:pytest.fail('status attempted source bytes'))
    monkeypatch.setattr(subject,'analyze_saved_inputs',lambda *a,**kw:pytest.fail('status attempted backend'))
    first=subject.status();second=subject.status()
    assert first==second and subject.BOOK.read_bytes()==before


@pytest.mark.parametrize('change',['manifest','manifest_hash','state','receipt','event_hash','event_body','event_previous','delete_terminal','extra_event','output_column'])
def test_status_rejects_saved_hash_chain_or_terminal_tampering(generated, state_machine, change):
    subject.run(generated/'first')
    with sqlite3.connect(subject.BOOK) as db:
        if change=='manifest':db.execute("UPDATE audits SET manifest='{}'")
        if change=='manifest_hash':db.execute("UPDATE audits SET manifest_hash=?",('0'*64,))
        if change=='state':db.execute("UPDATE audits SET state='CONSUMED'")
        if change=='receipt':db.execute("UPDATE audits SET receipt='{}'")
        if change=='output_column':db.execute('UPDATE audits SET output=?',(str(generated/'alias'),))
        if change=='event_hash':db.execute("UPDATE events SET event_hash=? WHERE ordinal=2",('0'*64,))
        if change=='event_body':db.execute("UPDATE events SET body='{}' WHERE ordinal=2")
        if change=='event_previous':db.execute("UPDATE events SET previous_hash=? WHERE ordinal=2",('0'*64,))
        if change=='delete_terminal':db.execute('DELETE FROM events WHERE ordinal=2')
        if change=='extra_event':
            prior=db.execute('SELECT event_hash FROM events WHERE ordinal=2').fetchone()[0]
            body={'subject':subject.SUBJECT,'ordinal':3,'previous_hash':prior,'phase':'COMPLETE','payload':{}}
            db.execute('INSERT INTO events VALUES(?,?,?,?,?)',(subject.SUBJECT,3,serial(body),prior,digest(body)))
    with pytest.raises((ValueError,KeyError)):subject.status()


@pytest.mark.parametrize('change',['receipt_subject','receipt_success'])
def test_terminal_semantic_tampering_is_rejected_even_with_updated_receipt_event_hash(generated,state_machine,change):
    subject.run(generated/'first')
    with sqlite3.connect(subject.BOOK) as db:
        receipt=json.loads(db.execute('SELECT receipt FROM audits').fetchone()[0])
        if change=='receipt_subject':receipt['subject']='different-scope'
        else:receipt['formal_target_success']=True
        terminal=json.loads(db.execute('SELECT body FROM events WHERE ordinal=2').fetchone()[0])
        terminal['payload']['receipt_sha256']=digest(receipt)
        db.execute('UPDATE audits SET receipt=?',(serial(receipt),))
        db.execute('UPDATE events SET body=?,event_hash=? WHERE ordinal=2',(serial(terminal),digest(terminal)))
    with pytest.raises(ValueError,match='scope or success'):subject.status()


def test_lineage_book_never_connects_to_original_evaluation_custody(generated,state_machine,monkeypatch):
    connect=sqlite3.connect;seen=[]
    def guarded(database,*args,**kwargs):
        text=str(database);assert 'evaluation_custody.sqlite3' not in text
        assert text==str(subject.BOOK) or text.startswith(subject.BOOK.resolve().as_uri())
        seen.append(text);return connect(database,*args,**kwargs)
    monkeypatch.setattr(subject.sqlite3,'connect',guarded)
    subject.run(generated/'first');subject.status()
    assert seen and all('input_lineage_audits.sqlite3' in value for value in seen)


@pytest.mark.parametrize('mode',['run','status'])
def test_cli_selects_only_explicit_mode_without_real_book(generated,monkeypatch,capsys,mode):
    calls=[];result={'subject':'generated-cli','state':'CONSUMED','event_count':1,'receipt':None,'formal_target_success':False}
    monkeypatch.setattr(subject,'run',lambda path:(calls.append(('run',path)) or result))
    monkeypatch.setattr(subject,'status',lambda :(calls.append(('status',None)) or result))
    args=['--run-output',str(generated/'output')] if mode=='run' else ['--status']
    monkeypatch.setattr(sys,'argv',[str(CLI),*args]);runpy.run_path(str(CLI),run_name='__main__')
    printed=json.loads(capsys.readouterr().out)
    assert printed==result and calls==[(mode,str(generated/'output') if mode=='run' else None)]
    assert not subject.BOOK.exists()


@pytest.mark.parametrize('arguments',[[],['--run-output','generated','--status'],['--release-sealed']])
def test_cli_rejects_ambiguous_or_unsupported_mode_without_calling_backend(generated,monkeypatch,arguments):
    monkeypatch.setattr(subject,'run',lambda *a:pytest.fail('invalid CLI dispatched'))
    monkeypatch.setattr(subject,'status',lambda *a:pytest.fail('invalid CLI inspected real book'))
    monkeypatch.setattr(sys,'argv',[str(CLI),*arguments])
    with pytest.raises(SystemExit) as error:runpy.run_path(str(CLI),run_name='__main__')
    assert error.value.code==2 and not subject.BOOK.exists()
